version: '3.4'

services:
  vmori:
    image: ${DOCKER_REGISTRY-}vmori
    build:
      context: ../
      dockerfile: ./src/VMori/Dockerfile
    environment:
        - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
        - Storage__ConnectionStrings=${Storage__ConnectionStrings}
        - Storage__Domain=${Storage__Domain}
        - Mail__ApiKey=${Mail__ApiKey}
        - Mail__SystemMailAddress=${Mail__SystemMailAddress}
        - Mail__SupportMailAddress=${Mail__SupportMailAddress}
        - Client__Domain=${Client__Domain}
        - Youtube__ApiKey=${Youtube__ApiKey}
    ports:
        - 5678:443
